[package]
name = "sira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
crossbeam = "0.8.2"
openssh = "0.9"
regex = "1.9"
