[package]
name = "sira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9"
tokio = { version = "1", features = ["sync"] }
openssh = "0.9"
